[[puzzles]]
label = "Zoe Summer"
slug = "zoe-summer"
src = "puzzles/zoe-summer.jpg"
credit_text = "puzzle art by @moochisukii"
credit_url = "https://x.com/moochisukii"

[[puzzles]]
label = "Zoe Assassin"
slug = "zoe-assassin"
src = "puzzles/zoe-assassin.jpg"

[[puzzles]]
label = "Zoe Samurai"
slug = "zoe-samurai"
src = "puzzles/zoe-samurai.jpg"

[[puzzles]]
label = "Zoe Potter"
slug = "zoe-potter"
src = "puzzles/zoe-potter.jpg"

[[puzzles]]
label = "Raora by Noy"
slug = "raora-by-noy"
src = "puzzles/raora-by-noy.avif"
