[package]
name = "heddobureika-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
heddobureika-core.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
rand.workspace = true
url.workspace = true
base64.workspace = true
p256 = { workspace = true, features = ["ecdsa"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
mime_guess.workspace = true

futures-util.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tokio-tungstenite = { workspace = true, features = ["rustls-tls-native-roots"] }
rustls = { workspace = true, features = ["ring"] }
