[package]
name = "heddobureika-image-pipeline"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
image = { workspace = true, features = ["png", "jpeg", "webp", "avif"] }
img-parts.workspace = true
moxcms.workspace = true
png.workspace = true
thiserror.workspace = true

[features]
default = []
